---
- name: set next server in cobbler settings
  lineinfile: dest=/etc/cobbler/settings regexp='^next_server' line='next_server:'{{ rpc_prep_ip }}

- name: set server in cobbler settings
  lineinfile: dest=/etc/cobbler/settings regexp='^server' line='server:'{{ rpc_prep_ip }}

- name: dhcp interface
  lineinfile: dest=/etc/default/isc-dhcp-server regexp='^INTERFACES=' line="INTERFACES="{{ dhcp_interfaces }}

- name: dhcp config
  template: src=templates/cobbler_dhcp.j2 dest=/etc/cobbler/dhcp.template

- name: import image to cobbler
  command: cobbler import --name=ubuntu-14.04.4-server-amd64 --path=/root/ubuntu-14.04.3-server-amd64

- name: delete image
  file: path=/opt/ubuntu-14.04.3-server-amd64 state=absent

- name: get sources.list file
  get_url: url=https://raw.githubusercontent.com/jameswthorne/default-ubuntu-sources.list/master/trusty-sources.list dest=/var/www/html/trusty-sources.list
