---

- include: repo.yml

- include: dependencies_deb.yml
  when: ansible_os_family == "Debian"

- include: dependencies_redhat.yml
  when: ansible_os_family == "RedHat"

- name: Install Jenkins for Debian
  apt: name=jenkins state=latest
  register: jenkins_install
  when: ansible_os_family == "Debian"

- name: Install Jenkins for RedHat
  yum: name=jenkins state=latest
  register: jenkins_install
  when: ansible_os_family == "RedHat"

- name: Install Jenkins for FreeBSD
  pkgng: name=jenkins state=present
  register: jenkins_install
  when: ansible_os_family == "FreeBSD"

- name: Ensure jenkins is running
  service:
    name: jenkins
    state: started
  when: ansible_os_family == "RedHat" or ansible_os_family == "FreeBSD"

- name: Start jenkins on boot
  shell: chkconfig jenkins on
  when: ansible_os_family == "RedHat"

- name: Ensure jenkins is running and starting on boot
  service:
    name: jenkins
    state: started
    enabled: yes
  when: ansible_os_family == "FreeBSD"

- include: config.yml

- include: cli.yml

#- include: plugins.yml

#- include: jobs.yml

#SET UP GIT USER/SSH KEY/HOST KEY VERIFICATION
#PULL IN JOBS
#SET RANDOM CONFIG VALS i.e. SECRET TEXTS AND FILES
#PASSWORDLESS SUDO

#- include: config.yml
